#!/bin/sh
# Stamp the build time into index.html before every commit.
TIMESTAMP=$(date '+%d %b %Y %H:%M')
if [ "$(uname)" = "Darwin" ]; then
  sed -i '' "s/const BUILD_TIME = '[^']*'/const BUILD_TIME = '$TIMESTAMP'/" index.html
else
  sed -i "s/const BUILD_TIME = '[^']*'/const BUILD_TIME = '$TIMESTAMP'/" index.html
fi
git add index.html
